### ISSUE TITLE
0.5.0: Command renameCollection failed: target namespace exists.

### ISSUE THREAD

**Issue by rajivkukreja** [sergeyzwezdin/Hangfire.Mongo#93]
Greetings folks -

Just tried your new 0.5.0 release and getting the following error:

`Failed to configure mongo connection: Command renameCollection failed: target namespace exists.`

Here's my code for reference:
```
try
                {
                    HostingEnvironment.RegisterObject(this);
                    Log.InfoFormat("Configuring Mongo connection: {0}", Config.HangfireDatabaseConnectionString);
                    if (GlobalConfiguration.Configuration == null)
                        throw new Exception("Hangfire.GlobalConfiguration.Configuration is null!");

                    var migrationOptions = new MongoMigrationOptions
                    {
                        Strategy = MongoMigrationStrategy.None
                    };
                    var storageOptions = new MongoStorageOptions
                    {
                        MigrationOptions = migrationOptions
                    };

                    GlobalConfiguration.Configuration.UseMongoStorage(Config.HangfireDatabaseConnectionString, Config.HangfireDatabase, storageOptions);
                    
                }
                catch (Exception e)
                {
                    Log.ErrorFormat("Failed to configure mongo connection: {0}", e.Message);
                    throw;
                }
```

The error persists even after manually deleting all prior collections (`hangfire.*` only) in the hangfire db. Note that my hangfire db has 2 other collections (as seen below)

<img width="217" alt="screen shot 2017-08-21 at 3 52 14 pm" src="https://user-images.githubusercontent.com/11480340/29535679-c9f56650-8688-11e7-8422-4b80871dd84e.png">
 
These are unrelated to Hangfire.Mongo and I need to preserve them - so I did not delete them.

Thanks

**Comment by MarLoe** [comment]
The only renaming we do is to rename hangfire.statedata to hangfire.stateData. So I think that is where we should focus.
What is your setup. Could have had other instances running that might have conflicted?

**Comment by rajivkukreja** [comment]
Aha! When I first upgraded and deployed, it was without the MigrationOptions specified. I suspect this somehow led to a situation where the db now had both `hangfire.statedata` and `hangfire.stateData`. 

Subsequent attempts (even with MigrationOptions) then complained about not being able to rename (due to `hangfire.stateData` already existing). 

All I need to do to get out of this situation was to delete all `hangfire.*` objects again and restart. 

All is well now. I'm up and running with 0.5.0.

Thanks very much!

**Comment by MarLoe** [comment]
@rajivkukreja, still weird how you got into that situation in the first place.
I have added an extra check in the code, to avoid the exception you experienced.

**Comment by axle-h** [comment]
I have the same issue with the 0.5.0 release. Happens when we run a background server that runs a single background job that queues some recurring jobs then restart it. Before the restart we have these collections:

![image](https://user-images.githubusercontent.com/4509102/29811805-a0bd43ce-8c9c-11e7-8926-d4ddd3737b10.png)

Afterwards we have:

![image](https://user-images.githubusercontent.com/4509102/29811821-ae558b36-8c9c-11e7-8233-b994215a29da.png)

So you've created the old "statehash" collection somewhere. Probably in "src/Hangfire.Mongo/Migration/Steps/Version06/03_RecurringJobMigration.cs" which I'd assume runs before Version07 migration that renames the collection?

If we then try to restart again we get the "Hangfire.Mongo version: 0.5.0.0, introduces a new schema version that requires migration." InvalidOperationException.

**Comment by MarLoe** [comment]
@rajivkukreja, @axle-h,
Just released 0.5.1 that should fix this problem. Please let me know of the outcome.

**Comment by MarLoe** [comment]
@rajivkukreja, seems like you reopened the wrong issue. I am reopening this instead: #70 and closing this one.

**Comment by axle-h** [comment]
0.5.1 seems to have fixed this issue thanks
